# Generated by Django 2.0.5 on 2018-06-05 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20170410_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_num',
            field=models.IntegerField(default=1540820109),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='p', to='rbac.Menu'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rbac.Menu'),
        ),
        migrations.AlterField(
            model_name='permission2action',
            name='a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rbac.Action'),
        ),
        migrations.AlterField(
            model_name='permission2action',
            name='p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rbac.Permission'),
        ),
        migrations.AlterField(
            model_name='permission2action2role',
            name='p2a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rbac.Permission2Action'),
        ),
        migrations.AlterField(
            model_name='permission2action2role',
            name='r',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rbac.Role'),
        ),
        migrations.AlterField(
            model_name='user2role',
            name='r',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rbac.Role'),
        ),
        migrations.AlterField(
            model_name='user2role',
            name='u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rbac.User'),
        ),
    ]
