# Generated by Django 2.0.5 on 2018-06-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20180605_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student_num',
        ),
    ]
