# Generated by Django 2.0.5 on 2018-06-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_remove_user_student_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_id',
            field=models.CharField(default=1540820109, max_length=64),
            preserve_default=False,
        ),
    ]
